fetch('https://opponents-district-slides-detection.trycloudflare.com/home', {
	method: 'POST',
	body: `{
  "zen": "Practicality beats purity.",
  "hook_id": 329559734,
  "hook": {
    "type": "Repository",
    "id": 329559734,
    "name": "web",
    "active": true,
    "events": [
      "*"
    ],
    "config": {
      "content_type": "form",
      "insecure_ssl": "0",
      "url": "https://identical-albert-unsigned-married.trycloudflare.com/"
    },
    "updated_at": "2021-11-21T16:33:50Z",
    "created_at": "2021-11-21T16:33:50Z",
    "url": "https://api.github.com/repos/Tricked-dev/diplo/hooks/329559734",
    "test_url": "https://api.github.com/repos/Tricked-dev/diplo/hooks/329559734/test",
    "ping_url": "https://api.github.com/repos/Tricked-dev/diplo/hooks/329559734/pings",
    "deliveries_url": "https://api.github.com/repos/Tricked-dev/diplo/hooks/329559734/deliveries",
    "last_response": {
      "code": null,
      "status": "unused",
      "message": null
    }
  },
  "repository": {
    "id": 415401762,
    "node_id": "R_kgDOGMKHIg",
    "name": "diplo",
    "full_name": "Tricked-dev/diplo",
    "private": false,
    "owner": {
      "login": "Tricked-dev",
      "id": 72335827,
      "node_id": "MDQ6VXNlcjcyMzM1ODI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/72335827?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Tricked-dev",
      "html_url": "https://github.com/Tricked-dev",
      "followers_url": "https://api.github.com/users/Tricked-dev/followers",
      "following_url": "https://api.github.com/users/Tricked-dev/following{/other_user}",
      "gists_url": "https://api.github.com/users/Tricked-dev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Tricked-dev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Tricked-dev/subscriptions",
      "organizations_url": "https://api.github.com/users/Tricked-dev/orgs",
      "repos_url": "https://api.github.com/users/Tricked-dev/repos",
      "events_url": "https://api.github.com/users/Tricked-dev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Tricked-dev/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Tricked-dev/diplo",
    "description": "A script runner for deno. 🚀🚀🚀",
    "fork": false,
    "url": "https://api.github.com/repos/Tricked-dev/diplo",
    "forks_url": "https://api.github.com/repos/Tricked-dev/diplo/forks",
    "keys_url": "https://api.github.com/repos/Tricked-dev/diplo/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Tricked-dev/diplo/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Tricked-dev/diplo/teams",
    "hooks_url": "https://api.github.com/repos/Tricked-dev/diplo/hooks",
    "issue_events_url": "https://api.github.com/repos/Tricked-dev/diplo/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Tricked-dev/diplo/events",
    "assignees_url": "https://api.github.com/repos/Tricked-dev/diplo/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Tricked-dev/diplo/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Tricked-dev/diplo/tags",
    "blobs_url": "https://api.github.com/repos/Tricked-dev/diplo/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Tricked-dev/diplo/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Tricked-dev/diplo/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Tricked-dev/diplo/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Tricked-dev/diplo/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Tricked-dev/diplo/languages",
    "stargazers_url": "https://api.github.com/repos/Tricked-dev/diplo/stargazers",
    "contributors_url": "https://api.github.com/repos/Tricked-dev/diplo/contributors",
    "subscribers_url": "https://api.github.com/repos/Tricked-dev/diplo/subscribers",
    "subscription_url": "https://api.github.com/repos/Tricked-dev/diplo/subscription",
    "commits_url": "https://api.github.com/repos/Tricked-dev/diplo/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Tricked-dev/diplo/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Tricked-dev/diplo/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Tricked-dev/diplo/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Tricked-dev/diplo/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Tricked-dev/diplo/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Tricked-dev/diplo/merges",
    "archive_url": "https://api.github.com/repos/Tricked-dev/diplo/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Tricked-dev/diplo/downloads",
    "issues_url": "https://api.github.com/repos/Tricked-dev/diplo/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Tricked-dev/diplo/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Tricked-dev/diplo/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Tricked-dev/diplo/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Tricked-dev/diplo/labels{/name}",
    "releases_url": "https://api.github.com/repos/Tricked-dev/diplo/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Tricked-dev/diplo/deployments",
    "created_at": "2021-10-09T19:20:16Z",
    "updated_at": "2021-11-20T12:41:16Z",
    "pushed_at": "2021-11-20T12:41:13Z",
    "git_url": "git://github.com/Tricked-dev/diplo.git",
    "ssh_url": "git@github.com:Tricked-dev/diplo.git",
    "clone_url": "https://github.com/Tricked-dev/diplo.git",
    "svn_url": "https://github.com/Tricked-dev/diplo",
    "homepage": "https://tricked.pro/diplo",
    "size": 488,
    "stargazers_count": 19,
    "watchers_count": 19,
    "language": "Rust",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "allow_forking": true,
    "is_template": false,
    "topics": [
      "deno",
      "denoland",
      "package",
      "package-manager",
      "rust",
      "rust-lang",
      "script",
      "script-runner"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 19,
    "default_branch": "main"
  },
  "sender": {
    "login": "Tricked-dev",
    "id": 72335827,
    "node_id": "MDQ6VXNlcjcyMzM1ODI3",
    "avatar_url": "https://avatars.githubusercontent.com/u/72335827?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Tricked-dev",
    "html_url": "https://github.com/Tricked-dev",
    "followers_url": "https://api.github.com/users/Tricked-dev/followers",
    "following_url": "https://api.github.com/users/Tricked-dev/following{/other_user}",
    "gists_url": "https://api.github.com/users/Tricked-dev/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Tricked-dev/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Tricked-dev/subscriptions",
    "organizations_url": "https://api.github.com/users/Tricked-dev/orgs",
    "repos_url": "https://api.github.com/users/Tricked-dev/repos",
    "events_url": "https://api.github.com/users/Tricked-dev/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Tricked-dev/received_events",
    "type": "User",
    "site_admin": false
  }
}`,
});
